name: Build and Analyze

on:
  workflow_dispatch:
  push:    
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:/home/runner/.dotnet/tools"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"gabrielrabreu_Haseroz.TestKit.DotNet" \
            /o:"abreu-dev" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml \
            /d:sonar.sources="src/Haseroz.TestKit,sample/Haseroz.TestKit.Sample" \
            /d:sonar.tests="tests/Haseroz.TestKit.UnitTest,sample/Haseroz.TestKit.Sample.FunctionalTests" \
            /d:sonar.exclusions="tests/Haseroz.TestKit.UnitTest,sample/Haseroz.TestKit.Sample.FunctionalTests"
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"